### PR TITLE
WIP: Allow for creation of recurring and adhoc subscriptions

### PR DESCRIPTION
**Pull request by jacques**
Add support for creating a recurring subscription (i.e. monthly payment via card for R 99) or adhoc (i.e. R 10 airtime voucher when the user requests the payment).

### CODE REVIEW

**Comment by jacques** [comment]
Sorry I have included a security patch here.  Can this be merged ASAP?  The code coverage I will look at and submit another pull request for.

**Comment by delatbabel** [comment]
If you need this in a tagged release please let me know, please verify that it works in a production environment first.

**Comment by jacques** [comment]
Please tag (I've tagged my fork for use with production).

**Comment by delatbabel** [comment]
Released as v2.2

**Pull request merged**
