### PR TITLE
Fix for ITN support with using a passphrase configured via the PayFast website

### PR DESCRIPTION
**Pull request by jacques**

### CODE REVIEW

**Comment by delatbabel** [comment]
OK thanks for the contribution. If you can confirm that it works in production I will tag for release.

**Comment by jacques** [comment]
Thanks!  Confirmed that it's working on PayFast's sandbox and production.

**Comment by delatbabel** [comment]
Released in v2.1.3

**Comment by jacques** [comment]
Thanks!

**Pull request merged**
