### PR TITLE
Updated package to use omnipay v3 library

### PR DESCRIPTION
**Pull request by robjmills**
This is a PR to make the package compatible with V3 of the Omnipay library, which is required for Symfony 3+ and associated components.

### CODE REVIEW

**Comment by barryvdh** [comment]
Can you update the Travis build to fix the tests?

**Comment by barryvdh** [comment]
Thanks!

**Comment by robjmills** [comment]
Thanks for getting on to that so quickly @barryvdh!

Will you be tagging a V3 release with this? Just conscious that that is a breaking change potentially for people with other Omnipay libs on V2 or Symfony 2 components. This would also be the case with the 2Checkout PR.

**Comment by barryvdh** [comment]
yeah doen

**Pull request merged**
