### PR TITLE
Allow Guzzle 7 support

### PR DESCRIPTION
**Pull request by mnwalker**

### CODE REVIEW

**Comment by jacques** [comment]
@barryvdh any chances of merging this pull request?

**Comment by barryvdh** [comment]
There shouldn't even be a dependency on guzzle actually.

**Comment by jacques** [comment]
@barryvdh any chances of tagging so I don't have to remember to require omnipay/payfast as dev-master?

**Comment by barryvdh** [comment]
Done

**Comment by jacques** [comment]
Thank you!

**Pull request merged**
